[build]
publish = "public"
command = "hugo --gc --minify"
baseUrl = "https://storj.io/blog"

[context.production.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.3"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/2020/03/building-tardigrade-connectors/"
to = "https://tardigrade.io/blog/post/community/building-tardigrade-connectors/"
status = 301
force = true

[[redirects]]
from = "/2020/02/use-cases-for-the-decentralized-cloud/"
to = "https://tardigrade.io/blog/post/tutorials/use-cases-for-the-decentralized-cloud/"
status = 301
force = true

[[redirects]]
from = "/2020/01/announcing-early-access-for-tardigrade/"
to = "https://tardigrade.io/blog/post/business/announcing-early-access-for-tardigrade/"
status = 301
force = true

[[redirects]]
from = "/2020/01/what-to-expect-in-production/"
to = "https://tardigrade.io/blog/post/community/what-to-expect-in-production/"
status = 301
force = true

[[redirects]]
from = "/2019/12/secure-access-control-in-the-decentralized-cloud/"
to = "https://tardigrade.io/blog/post/engineering/secure-access-control-in-the-decentralized-cloud/"
status = 301
force = true

[[redirects]]
from = "/2019/11/announcing-pioneer-2-and-tardigrade.io-pricing/"
to = "https://tardigrade.io/blog/post/business/announcing-pioneer-2-and-tardigrade-io-pricing-1/"
status = 301
force = true

[[redirects]]
from = "/2019/11/measuring-production-readiness-using-qualification-gates/"
to = "https://tardigrade.io/blog/post/engineering/measuring-production-readiness-using-qualification-gates/"
status = 301
force = true

[[redirects]]
from = "/2019/10/architecting-a-decentralized-github-backup/"
to = "https://tardigrade.io/blog/post/community/architecting-a-decentralized-github-backup/"
status = 301
force = true

[[redirects]]
from = "/2019/10/ipfs-now-on-storj-network/"
to = "https://tardigrade.io/blog/post/business/ipfs-now-on-storj-network/"
status = 301
force = true

[[redirects]]
from = "/2019/08/the-role-of-qualification-gates-in-getting-to-beta-and-beyond/"
to = "https://tardigrade.io/blog/post/engineering/the-role-of-qualification-gates-in-getting-to-beta-and-beyond/"
status = 301
force = true

[[redirects]]
from = "/2019/08/announcing-beta-pioneer-1-v3-and-tardigrade-are-here/"
to = "https://tardigrade.io/blog/post/engineering/announcing-beta-pioneer-1-v3-and-tardigrade-are-here/"
status = 301
force = true

[[redirects]]
from = "/2019/07/introducing-the-tardigrade-mascot/"
to = "https://tardigrade.io/blog/post/community/introducing-the-tardigrade-mascot/"
status = 301
force = true

[[redirects]]
from = "/2019/07/help-us-choose-the-tardigrade-mascot/"
to = "https://tardigrade.io/blog/post/community/help-us-choose-the-tardigrade-mascot/"
status = 301
force = true

[[redirects]]
from = "/2019/07/announcing-beacon-alpha-file-sharing-ip-filtering-and-increased-performance/"
to = "https://tardigrade.io/blog/post/engineering/announcing-beacon-alpha-file-sharing-ip-filtering-and-increased-performance/"
status = 301
force = true

[[redirects]]
from = "/2019/06/ip-filtering-keeps-data-distributed/"
to = "https://tardigrade.io/blog/post/engineering/ip-filtering-keeps-data-distributed/"
status = 301
force = true

[[redirects]]
from = "/2019/05/flexible-file-sharing-with-macaroons/"
to = "https://tardigrade.io/blog/post/engineering/flexible-file-sharing-with-macaroons/"
status = 301
force = true

[[redirects]]
from = "/2019/05/coordination-avoidance-on-the-storj-network/"
to = "https://tardigrade.io/blog/post/engineering/coordination-avoidance-on-the-storj-network/"
status = 301
force = true

[[redirects]]
from = "/2019/04/what-happens-when-you-upload-a-file-to-a-decentralized-network/"
to = "https://tardigrade.io/blog/post/engineering/what-happens-when-you-upload-a-file-to-a-decentralized-network/"
status = 301
force = true

[[redirects]]
from = "/2019/04/the-storj-v3-developer-library-has-arrived/"
to = "https://tardigrade.io/blog/post/engineering/the-storj-v3-developer-library-has-arrived/"
status = 301
force = true

[[redirects]]
from = "https://storj.io/blog/2019/04/starting-your-first-project-on-the-tardigrade-cloud-storage-network/"
to = "https://tardigrade.io/blog/post/engineering/starting-your-first-project-on-the-tardigrade-cloud-storage-network/"
status = 301
force = true

[[redirects]]
from = "/2019/04/developers-and-v3-network-make-first-contact-with-vanguard-alpha/"
to = "https://tardigrade.io/blog/post/engineering/developers-and-v3-network-make-first-contact-with-vanguard-alpha/"
status = 301
force = true

[[redirects]]
from = "/2019/04/cloud-storage-prices-havent-changed-much-in-4-years-but-theyre-about-to/"
to = "https://tardigrade.io/blog/post/business/cloud-storage-prices-havent-changed-much-in-4-years-theyre-about-to/"
status = 301
force = true

[[redirects]]
from = "/2019/02/planning-ahead-for-the-v2-to-v3-network-transition/"
to = "https://tardigrade.io/blog/post/community/planning-ahead-for-the-v2-to-v3-network-transition/"
status = 301
force = true

[[redirects]]
from = "/2019/02/announcing-the-storj-v3-explorer-release/"
to = "https://tardigrade.io/blog/post/community/announcing-the-storj-v3-explorer-release/"
status = 301
force = true

[[redirects]]
from = "/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/"
to = "https://tardigrade.io/blog/post/engineering/getting-from-petabytes-to-exabytes-the-road-ahead/"
status = 301
force = true
